{"name": "test_logging_with_invalid_credential", "status": "passed", "start": 1711016928679, "stop": 1711016930727, "uuid": "22a86d2f-4e7d-4796-93f3-47f7c3352a4c", "historyId": "6413b573082a7f6b0d02eafce6fa07d9", "testCaseId": "6413b573082a7f6b0d02eafce6fa07d9", "fullName": "tests.Login_Test.TestLogin#test_logging_with_invalid_credential", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "Login_Test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-4VA98U9"}, {"name": "thread", "value": "16988-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Login_Test"}]}