{"name": "test_logging_with_invalid_credential", "status": "passed", "start": 1710846820145, "stop": 1710846822076, "uuid": "8e1e0b83-6168-4429-bfa5-3eb93622b314", "historyId": "6413b573082a7f6b0d02eafce6fa07d9", "testCaseId": "6413b573082a7f6b0d02eafce6fa07d9", "fullName": "tests.Login_Test.TestLogin#test_logging_with_invalid_credential", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "Login_Test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-4VA98U9"}, {"name": "thread", "value": "10260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Login_Test"}]}